apiVersion: v1
kind: ServiceAccount
metadata:
  name: algorithm-builder-serviceaccount
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-builder
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: algorithm-builder
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-builder
    core: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: algorithm-builder
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-builder
    core: "true"
subjects:
- kind: ServiceAccount
  name: algorithm-builder-serviceaccount
roleRef:
  kind: Role
  name: algorithm-builder
  apiGroup: rbac.authorization.k8s.io
---
{{- if (eq .Values.global.k8senv "openshift") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: algorithm-builder-openshift
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-builder
    core: "true"
subjects:
- kind: ServiceAccount
  name: algorithm-builder-serviceaccount
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}