apiVersion: v1
kind: ServiceAccount
metadata:
  name: algorithm-operator-serviceaccount
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-operator
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: algorithm-operator
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-operator
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: [create, delete, deletecollection, get, list, patch, update, watch]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: [create, delete, deletecollection, get, list, patch, update, watch]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: [create, delete, deletecollection, get, list, patch, update, watch]
- apiGroups:
  - ""
  resources:
  - services
  verbs: [create, delete, deletecollection, get, list, patch, update, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: algorithm-operator
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.labels.group.value }}
    app: algorithm-operator
    core: "true"
subjects:
- kind: ServiceAccount
  name: algorithm-operator-serviceaccount
roleRef:
  kind: Role
  name: algorithm-operator
  apiGroup: rbac.authorization.k8s.io
---
