kind: Service
apiVersion: v1
metadata:
  name: algorithm-queue-svc
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: algorithm-queue-svc
    chart: algorithm-queue-svc
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics: "true"
spec:
  ports:
    - port: {{ .Values.algorithm_queue_svc.env.metric_port }}
      targetPort: {{ .Values.algorithm_queue_svc.env.metric_port }}
      protocol: TCP
      name: metrics
  selector:
    metrics-group: 'algorithm-queue'