kind: Service
apiVersion: v1
metadata:
  name: algorithm-debug
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: algorithm-debug
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics: "true"
spec:
  selector:
    metrics-group: algorithm-debug
    group: {{ .Values.labels.group.value }}
  clusterIP: None