apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-serviceaccount
  labels:
    group: {{ .Values.labels.group.value }}
    app: api-server
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: api-server
  labels:
    group: {{ .Values.labels.group.value }}
    app: api-server
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get", "list", "watch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.labels.group.value }}
    app: api-server
    core: "true"
subjects:
- kind: ServiceAccount
  name: api-server-serviceaccount
roleRef:
  kind: Role
  name: api-server
  apiGroup: rbac.authorization.k8s.io
---
