apiVersion: v1
kind: Service
metadata:
  name: api-server
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics: "true"
spec:
  type: {{ index .Values "api_server" "service" "type" }}
  ports:
    - port: {{ index .Values "api_server" "env" "port" }}
      targetPort: {{ index .Values "api_server" "env" "port" }}
      protocol: TCP
      name: rest
    - port: {{ index .Values "api_server" "env" "metric_port" }}
      targetPort: {{ index .Values "api_server" "env" "metric_port" }}
      protocol: TCP
      name: metrics
  selector:
    app: api-server
    release: api-server
