{{- if index .Values "api_server" "ingress" "enabled" -}}
{{- $ingressPath := .Values.api_server.ingress.path -}}
{{- $fullName := "api-server" -}}
{{- $servicePort := .Values.api_server.env.port | int -}}
apiVersion:  {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: api-server
  annotations:
{{- if eq .Values.global.ingress.class "nginx"}}
{{- if .Values.global.ingress.use_regex }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.global.ingress.requireTls | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.global.ingress.maxBodySize | quote }}
{{- else if eq .Values.global.ingress.class "haproxy"}}
{{- if .Values.global.ingress.use_regex }}
    haproxy.router.openshift.io/rewrite-target: /$2
{{- else }}
    haproxy.router.openshift.io/rewrite-target: /
{{- end }}
    haproxy.router.openshift.io/ssl-redirect: {{ .Values.global.ingress.requireTls | quote }}
    haproxy.router.openshift.io/proxy-body-size: {{ .Values.global.ingress.maxBodySize | quote }}
{{- end}}
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
{{- if .Values.global.ingress.hostname }}
    kubernetes.io/tls-acme: "true"
{{- end }}  
  labels:
    app: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
{{- if .Values.global.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.global.ingress.hostname }}
    secretName: {{ $fullName }}-tls-secret
{{- end }}
  rules:
    - http:
        paths:
{{- if .Values.global.ingress.use_regex }}
        - path: {{ .Values.global.ingress.prefix }}{{ $ingressPath }}(/|$)(.*)
{{- else }}
        - path: {{ .Values.global.ingress.prefix }}{{ $ingressPath }}/
{{- end }}
          backend: {{- include "ingress.backend" (dict "serviceName" $fullName "servicePort" $servicePort "context" $) | nindent 12 }}
          {{- if eq "true" (include "ingress.supportsPathType" .) }}
          pathType: ImplementationSpecific
          {{- end }}
{{- if .Values.global.ingress.hostname }}
      host: {{ .Values.global.ingress.hostname }}
{{- end }}
{{- end }}