{{- if index .Values "api_server" "ingress" "enabled" -}}
{{- $fullName := "api-server" -}}
{{- $servicePort := index .Values "api_server" "env" "port" -}}
{{- $ingressPath := index .Values "api_server" "ingress" "path" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.requireTls | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize | quote }}
{{- if .Values.ingress.hostname }}
    kubernetes.io/tls-acme: "true"
{{- end }}    
  labels:
    app: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
{{- if .Values.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ $fullName }}-tls-secret
{{- end }}
  rules:
    - http:
        paths:
        - path: {{ .Values.ingress.prefix }}{{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname }}
{{- end }}
{{- end }}