apiVersion: v1
kind: Service
metadata:
  name: artifacts-registry
  labels:
    app: artifacts-registry
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  type: {{ index .Values "artifacts_registry" "service" "type" }}
  ports:
    - port: {{ index .Values "artifacts_registry" "env" "port" }}
      targetPort: 8081
      protocol: TCP
      name: web
  selector:
    app: artifacts-registry
    release: artifacts-registry
