apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
  labels:
    app: busybox
    group: {{ .Values.labels.group.value }}
    thirdparty: "true"
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: busybox
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}  
      containers:
      - image: "{{ .Values.global.registry }}{{ index .Values "busybox" "image" "repository" }}:{{ index .Values "busybox" "image" "tag" }}"
        command:
          - sleep
          - "1800"
        imagePullPolicy: IfNotPresent
        name: busybox
{{- if or .Values.global.resources_enable .Values.busybox.resources_enable }}
        resources:
          limits:
            cpu: 50m
            memory: 250Mi
{{- else }}
        resources: {}
{{- end }}
      terminationGracePeriodSeconds: 5  
      restartPolicy: Never