kind: Service
apiVersion: v1
metadata:
  name: caching-service
  labels:
    app: caching-service
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  selector:
    app: caching-service
  ports:
    - name: http
      port: {{ index .Values "caching_service" "env" "port" }}
      targetPort: {{ index .Values "caching_service" "env" "port" }}
