apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-serviceaccount
  labels:
    group: {{ .Values.lables.group.value }}
    app: cleanup
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cleanup
  labels:
    group: {{ .Values.lables.group.value }}
    app: cleanup
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup
  namespace: default
  labels:
    group: {{ .Values.lables.group.value }}
    app: cleanup
    core: "true"
subjects:
- kind: ServiceAccount
  name: cleanup-serviceaccount
roleRef:
  kind: Role
  name: cleanup
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-clusterrole
  labels:
    group: {{ .Values.lables.group.value }}
    app: cleanup
    core: "true"
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-clusterrolebinding
  labels:
    group: {{ .Values.lables.group.value }}
    app: cleanup
    core: "true"
subjects:
- kind: ServiceAccount
  name: cleanup-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: cleanup-clusterrole
  apiGroup: rbac.authorization.k8s.io
