apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  labels:
    app: dnsutils
    group: {{ .Values.labels.group.value }}
    thirdparty: "true"
spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
  imagePullSecrets:
    - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}  
  containers:
  - image: "{{ .Values.global.registry }}{{ .Values.dnsutils.image.repository }}:{{ .Values.dnsutils.image.tag }}"
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: dnsutils
{{- if .Values.global.resources_enable }}          
    resources:
      limits:
        cpu: 50m
        memory: 250Mi
{{- else }}
    resources: {}
{{- end }}
  terminationGracePeriodSeconds: 5  
  restartPolicy: Always