apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  pull-registry: {{ default "" .Values.build_secret.pull.registry | b64enc | quote }}
  pull-namespace: {{ default "" .Values.build_secret.pull.namespace | b64enc | quote }}
  pull-username: {{ default "" .Values.build_secret.pull.username | b64enc | quote }}
  pull-password: {{ default "" .Values.build_secret.pull.password | b64enc | quote }}
  
  push-registry: {{ default "" .Values.build_secret.push.registry | b64enc | quote }}
  push-namespace: {{ default "" .Values.build_secret.push.namespace | b64enc | quote }}
  push-username: {{ default "" .Values.build_secret.push.username | b64enc | quote }}
  push-password: {{ default "" .Values.build_secret.push.password | b64enc | quote }}