apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  docker_pull_registry: {{ .Values.global.registry | b64enc | quote }}
  docker_pull_namespace: {{ .Values.global.registry_namespace | b64enc | quote }}
  docker_pull_username: {{ .Values.global.registry_username | b64enc | quote }}
  docker_pull_password: {{ .Values.global.registry_password | b64enc | quote }}
  
  docker_push_registry: {{ .Values.build_secret.docker_registry | b64enc | quote }}
  {{ if and (not .Values.build_secret.docker_namespace) (.Values.build_secret.docker_username) }}
  docker_push_namespace: {{ .Values.build_secret.docker_username | b64enc | quote }}
  {{ else }}
  docker_push_namespace: {{ .Values.build_secret.docker_namespace | b64enc | quote }}
  {{ end }}
  docker_push_username: {{ .Values.build_secret.docker_username | b64enc | quote }}
  docker_push_password: {{ .Values.build_secret.docker_password | b64enc | quote }}
  
  npm_registry: {{ .Values.build_secret.npm_registry | b64enc | quote }}
  npm_token: {{ .Values.build_secret.npm_token | b64enc | quote }}
  pip_registry: {{ .Values.build_secret.pip_registry | b64enc | quote }}
  pip_token: {{ .Values.build_secret.pip_token | b64enc | quote }}