apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  pull-registry: {{ .Values.global.registry | b64enc | quote }}
  pull-namespace: {{ .Values.global.registry_namespace | b64enc | quote }}
  pull-username: {{ .Values.global.registry_username | b64enc | quote }}
  pull-password: {{ .Values.global.registry_password | b64enc | quote }}
  
  push-registry: {{ .Values.build_secret.registry | b64enc | quote }}
  {{ if and (not .Values.build_secret.namespace) (.Values.build_secret.username) }}
  push-namespace: {{ .Values.build_secret.username | b64enc | quote }}
  {{ else }}
  push-namespace: {{ .Values.build_secret.namespace | b64enc | quote }}
  {{ end }}
  push-username: {{ .Values.build_secret.username | b64enc | quote }}
  push-password: {{ .Values.build_secret.password | b64enc | quote }}