apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  username: {{ default "" .Values.docker_credentials_secret.username | b64enc | quote }}
  password: {{ default "" .Values.docker_credentials_secret.password | b64enc | quote }}
