apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  docker_pull_registry: {{ .Values.global.registry | trimSuffix "/" | b64enc | quote }}
  docker_pull_namespace: {{ .Values.global.registry_namespace | b64enc | quote }}
  docker_pull_username: {{ .Values.global.registry_username | b64enc | quote }}
  docker_pull_password: {{ .Values.global.registry_password | b64enc | quote }}
  docker_pull_insecure: {{ .Values.global.registry_insecure | toString | b64enc | quote }}
  docker_pull_skip_tls_verify: {{ .Values.global.registry_skip_tls_verify | toString | b64enc | quote }}
  
  docker_push_registry: {{ .Values.build_secret.docker_registry | trimSuffix "/" | b64enc | quote }}
  {{ if and (not .Values.build_secret.docker_namespace) (.Values.build_secret.docker_username) }}
  docker_push_namespace: {{ .Values.build_secret.docker_username | b64enc | quote }}
  {{ else }}
  docker_push_namespace: {{ .Values.build_secret.docker_namespace | b64enc | quote }}
  {{ end }}
  docker_push_username: {{ .Values.build_secret.docker_username | b64enc | quote }}
  docker_push_password: {{ .Values.build_secret.docker_password | b64enc | quote }}
  docker_push_insecure: {{ .Values.build_secret.docker_registry_insecure | toString | b64enc | quote }}
  docker_push_skip_tls_verify: {{ .Values.build_secret.docker_registry_skip_tls_verify | toString | b64enc | quote }}


  npm_registry: {{ .Values.build_secret.npm_registry | b64enc | quote }}
  npm_token: {{ .Values.build_secret.npm_token | b64enc | quote }}
  pip_registry: {{ .Values.build_secret.pip_registry | b64enc | quote }}
  pip_token: {{ .Values.build_secret.pip_token | b64enc | quote }}

  # pull-registry: {{ .Values.global.registry | b64enc | quote }}
  # pull-namespace: {{ .Values.global.registry_namespace | b64enc | quote }}
  # pull-username: {{ .Values.global.registry_username | b64enc | quote }}
  # pull-password: {{ .Values.global.registry_password | b64enc | quote }}
  
  # push-registry: {{ .Values.build_secret.docker_registry | b64enc | quote }}
  # {{ if and (not .Values.build_secret.docker_namespace) (.Values.build_secret.docker_username) }}
  # push-namespace: {{ .Values.build_secret.docker_username | b64enc | quote }}
  # {{ else }}
  # push-namespace: {{ .Values.build_secret.docker_namespace | b64enc | quote }}
  # {{ end }}
  # push-username: {{ .Values.build_secret.docker_username | b64enc | quote }}
  # push-password: {{ .Values.build_secret.docker_password | b64enc | quote }}  
