{{- if eq .Values.dsmetrics-storage.pvc.storage_class "-" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hkube-dsmetrics
  labels:
    group: {{ .Values.labels.group.value }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
    type: nfs
    role: hkube-dsmetrics
spec:
  capacity:
    storage: {{ .Values.dsmetrics-storage.pvc.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.dsmetrics-storage.pvc.nfs_server }}
    path: "{{ .Values.dsmetrics-storage.pvc.nfs_root }}/{{ .Values.global.clusterName }}/hkube-dsmetrics-storage"
{{- end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hkube-dsmetrics
  namespace: {{ .Release.Namespace }} 
  labels:
    group: {{ .Values.labels.group.value }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dsmetrics-storage.pvc.capacity }}
{{- if .Values.dsmetrics-storage.pvc.pv_name }}  
  volumeName: {{ .Values.dsmetrics-storage.pvc.pv_name }}
{{- else }}
{{- if eq .Values.dsmetrics-storage.pvc.storage_class "-" }}
  storageClassName: ""
  selector:
    matchLabels:
      group: {{ .Values.labels.group.value }}
      type: nfs
      role: hkube-datasource
{{- else if .Values.dsmetrics-storage.pvc.storage_class }}
  storageClassName: {{ .Values.dsmetrics-storage.pvc.storage_class }}
{{- end }}
  
{{- end }} 