{{- if .Values.etcd_defrag.enable }}
apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: etcd-defrag-cron
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  schedule: {{ .Values.etcd_defrag.pattern | quote }} 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 700
      template:
        spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
          imagePullSecrets:
            - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}
          serviceAccountName: gc-service
          containers:
          - name: etcd-defrag-cron
            image: {{ .Values.global.registry }}{{ .Values.etcd_defrag.image.repository }}:{{ .Values.etcd_defrag.image.tag }}
            env:
            - name: ETCD_COUNT
              value: {{ .Values.etcd.replicas | quote }}
            - name: ETCD_NAME
              value: {{ .Values.etcd_defrag.env.etcd_name | quote }}
            - name: ETCD_PROTOCOL
              value: {{ .Values.etcd_defrag.env.etcd_protocol | quote }}
            - name: ETCD_PORT
              value: {{ .Values.etcd_defrag.env.etcd_port | quote }}
            - name: SLEEP
              value: {{ .Values.etcd_defrag.env.sleep | quote }}
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
{{- if or .Values.global.resources_enable .Values.etcd_defrag.resources_enable }}
            resources:
{{ toYaml .Values.etcd_defrag.resources | indent 14 }}
{{- else }}
            resources: {}
{{- end }}               
          restartPolicy: Never
{{- end }}        