apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-cleaner
  labels:
    group: {{ .Values.lables.group.value }}
    core: "true"
    app: "etcd-cleaner"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcd-cleaner
            image: "{{ .Values.global.registry }}{{ index  .Values "etcd-cleaner" "image" "repository" }}:{{ index .Values "etcd-cleaner" "image" "tag" }}"
            resources:
            limits:
              cpu: 100m
              memory: 256Mi
            env:
            - name: "OBJECT_EXPIRATION_DAYS"
              valueFrom:
                configMapKeyRef:
                  name: etcd-cleaner-configmap
                  key: OBJECT_EXPIRATION_DAYS
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: Never
