{{- if .Values.etcd_defrag.enable }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-defrag-cron
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  schedule: {{ .Values.etcd_defrag.pattern | quote }} 
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      template:
        spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
          imagePullSecrets:
            - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}
          serviceAccountName: clean-old-jobs
          containers:
          - name: etcd-defrag-cron
            image: {{ .Values.global.registry }}{{ .Values.etcd_defrag.image.repository }}:{{ .Values.etcd_defrag.image.tag }}
{{- if or .Values.global.resources_enable .Values.etcd_defrag.resources_enable }}          
            resources:
{{ toYaml .Values.etcd_defrag.resources | indent 14 }}
{{- else }}
            resources: {}
{{- end }}               
          restartPolicy: Never
{{- end }}        