apiVersion: v1
kind: Service
metadata:
  name: gc-service
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: gc-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  type: {{ .Values.gc_service.service.type }}
  ports:
    - port: {{ .Values.gc_service.env.rest_port }}
      targetPort: {{ .Values.gc_service.env.rest_port }}
      protocol: TCP
      name: rest
  selector:
    app: gc-service
    release: gc-service
