apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-service
  labels:
    app: gc-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-service
      release: gc-service
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/gc-service-cm.yaml") . | sha256sum }}
      labels:
        app: gc-service
        release: gc-service
        group: {{ .Values.labels.group.value }}
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
{{ include "hkube.fluent_bit.volume" . | indent 8 }}
{{- if eq .Values.env.default_storage "fs" }}
        - name: storage-volume
          persistentVolumeClaim:
            claimName: hkube-storage-pvc
{{- end }}
      serviceAccountName: gc-service
      containers:
        - name: gc-service
          image: "{{ .Values.global.registry }}{{ .Values.gc_service.image.repository }}:{{ .Values.gc_service.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.gc_service.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.gc_service.healthcheck.path }}
              port: {{ .Values.gc_service.healthcheck.port }}
            initialDelaySeconds: {{ .Values.gc_service.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.gc_service.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.gc_service.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.gc_service.healthcheck.failureThreshold }}
{{- end }}
{{- if .Values.global.resources_enable }}
          resources:
{{ toYaml .Values.gc_service.resources | indent 12 }}
{{- else }}
          resources: {}
{{- end }}
          volumeMounts:
{{ include "hkube.fluent_bit.volumemount" . | indent 12 }}
{{- if eq .Values.env.default_storage "fs" }}
            - name: storage-volume
              mountPath: {{ .Values.global.storage.fs.base_directory | quote}}
{{- end }}
          ports:
            - containerPort: {{ .Values.gc_service.env.rest_port }}
              protocol: TCP
          env:
{{ include "hkube.fluent_bit.environment" . | indent 12 }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: NODE_ENV
            - name: HKUBE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: HKUBE_LOG_LEVEL
            - name: REST_PORT
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: REST_PORT
            - name: BASE_URL_PATH
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: BASE_URL_PATH
            - name: DATASOURCE_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DATASOURCE_CRON
            - name: DATASOURCE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DATASOURCE_ENABLED
            - name: DATASOURCE_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DATASOURCE_MAX_AGE
            - name: DATASOURCE_BASE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DATASOURCE_BASE_DIRECTORY
            - name: DATASOURCE_FOLDER_IN_USE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DATASOURCE_FOLDER_IN_USE
            - name: DEBUG_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DEBUG_ENABLED
            - name: DEBUG_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DEBUG_MAX_AGE
            - name: ETCD_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: ETCD_CRON
            - name: ETCD_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: ETCD_ENABLED
            - name: ETCD_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: ETCD_MAX_AGE
            - name: GATEWAY_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: GATEWAY_CRON
            - name: GATEWAY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: GATEWAY_ENABLED
            - name: GATEWAY_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: GATEWAY_MAX_AGE
            - name: JOBS_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: JOBS_CRON
            - name: JOBS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: JOBS_ENABLED 
            - name: JOBS_COMPLETED_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: JOBS_COMPLETED_MAX_AGE 
            - name: JOBS_FAILED_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: JOBS_FAILED_MAX_AGE
            - name: JOBS_PENDING_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: JOBS_PENDING_MAX_AGE
            - name: DEBUG_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DEBUG_CRON
            - name: PIPELINES_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: PIPELINES_CRON
            - name: PIPELINES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: PIPELINES_ENABLED
            - name: REDIS_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: REDIS_CRON
            - name: REDIS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: REDIS_ENABLED
            - name: REDIS_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: REDIS_MAX_AGE
            - name: STORAGE_CRON
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: STORAGE_CRON
            - name: STORAGE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: STORAGE_ENABLED
            - name: STORAGE_RESULT_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: STORAGE_RESULT_MAX_AGE
            - name: STORAGE_TEMP_MAX_AGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: STORAGE_TEMP_MAX_AGE
{{- if eq .Values.env.default_storage "fs" }}
            - name: BASE_FS_ADAPTER_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: BASE_FS_ADAPTER_DIRECTORY
{{- else if eq .Values.env.default_storage "s3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsSecret
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsEndpointUrl
{{- end }}
            - name: DEFAULT_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: DEFAULT_STORAGE
            - name: STORAGE_ENCODING
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: STORAGE_ENCODING                  
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: CLUSTER_NAME  
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INGRESS_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: gc-service-configmap
                  key: INGRESS_PREFIX
{{- if .Values.mongodb.enable }}
            - name: MONGODB_SERVICE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGODB_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: MONGODB_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-database
{{- end }}
{{ include "hkube.fluent_bit.sidecar" . | indent 8 }}
