{{- if eq .Values.env.default_storage "fs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hkube-storage-pv
  labels:
    group: {{ .Values.lables.group.value }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
    type: nfs
    role: hkube-storage
spec:
  capacity:
    storage: {{ .Values.global.storage.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.global.storage.nfs_server }}
    path: "{{ .Values.global.storage.fs.pvc.nfs_root }}/{{ .Values.global.clusterName }}/hkube-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hkube-storage-pvc
  namespace: default 
  labels:
    group: {{ .Values.lables.group.value }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.storage.capacity }}
  selector:
    matchLabels:
      group: {{ .Values.lables.group.value }}
      type: nfs
      role: hkube-storage
{{- end }} 