
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: hkube-gc
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: hkube-gc
  labels:
    group: {{ .Values.labels.group.value }}
    app: hkube-gc
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hkube-gc
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.labels.group.value }}
    app: hkube-gc
    core: "true"
subjects:
- kind: ServiceAccount
  name: hkube-gc
roleRef:
  kind: Role
  name: hkube-gc
  apiGroup: rbac.authorization.k8s.io
