{{- if and .Values.global.registry_password (not .Values.global.image_pull_secret.use_existing) }}
{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.global.registry_username }}
{{- $_ := set $registryAuthDocument "password" .Values.global.registry_password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $registryUrl := trimSuffix "/" .Values.global.registry }}
{{- $dockerAuthDocument := dict $registryUrl $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.image_pull_secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}