apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-old-jobs
  labels:
    app: clean-old-jobs
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-old-jobs
      release: clean-old-jobs
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/clean-old-jobs-cm.yaml") . | sha256sum }}
      labels:
        app: clean-old-jobs
        release: clean-old-jobs
        group: {{ .Values.labels.group.value }}
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: clean-old-jobs
      containers:
        - name: clean-old-jobs
          image: "{{ .Values.global.registry }}{{ index  .Values "clean_old_jobs" "image" "repository" }}:{{ index .Values "clean_old_jobs" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "image" "pullPolicy" }}
{{- if .Values.clean_old_jobs.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.clean_old_jobs.healthcheck.path }}
              port: {{ .Values.clean_old_jobs.healthcheck.port }}
            initialDelaySeconds: {{ .Values.clean_old_jobs.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.clean_old_jobs.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.clean_old_jobs.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.clean_old_jobs.healthcheck.failureThreshold }}
{{- end }}
{{- if or .Values.global.resources_enable .Values.clean_old_jobs.resources_enable }}          
          resources:
{{ toYaml .Values.clean_old_jobs.resources | indent 12 }}
{{- else }}
          resources: {}
{{- end }}     
          env:
{{ include "hkube.fluent_bit.environment" . | indent 12 }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: NODE_ENV
            - name: "MAX_COMPLETED_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_COMPLETED_JOB_AGE_HOURS
            - name: "MAX_FAILED_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_FAILED_JOB_AGE_HOURS
            - name: "MAX_PENDING_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_PENDING_JOB_AGE_HOURS
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{ include "hkube.fluent_bit.volumemount_full" . | indent 10 }}
{{ include "hkube.fluent_bit.sidecar" . | indent 8 }}
{{ include "hkube.fluent_bit.volume_full" . | indent 6 }}