apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: clean-old-jobs
  labels:
    app: clean-old-jobs
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-old-jobs
      release: clean-old-jobs
  template:
    metadata:
      labels:
        app: clean-old-jobs
        release: clean-old-jobs
        group: {{ .Values.lables.group.value }}
    spec:
      {{- if .Values.global.production }}
      nodeSelector:
        core: "true"
      {{- end }}
      serviceAccountName: clean-old-jobs
      containers:
        - name: clean-old-jobs
          image: "{{ index  .Values "clean-old-jobs" "image" "repository" }}:{{ index .Values "clean-old-jobs" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "image" "pullPolicy" }}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: NODE_ENV
            - name: "MAX_COMPLETED_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_COMPLETED_JOB_AGE_HOURS

