apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: clean-old-jobs
  labels:
    app: clean-old-jobs
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-old-jobs
      release: clean-old-jobs
  template:
    metadata:
      labels:
        app: clean-old-jobs
        release: clean-old-jobs
        group: {{ .Values.labels.group.value }}
    spec:
      {{- if and .Values.global.production (not .Values.global.namespaced)}}
      nodeSelector:
        core: "true"
      {{- end }}
      serviceAccountName: clean-old-jobs
      containers:
        - name: clean-old-jobs
          image: "{{ .Values.global.registry }}{{ index  .Values "clean_old_jobs" "image" "repository" }}:{{ index .Values "clean_old_jobs" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "image" "pullPolicy" }}
          resources:
{{ toYaml .Values.clean_old_jobs.resources | indent 12 }} 
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: NODE_ENV
            - name: "MAX_COMPLETED_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_COMPLETED_JOB_AGE_HOURS
            - name: "MAX_FAILED_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_FAILED_JOB_AGE_HOURS
            - name: "MAX_PENDING_JOB_AGE_HOURS"
              valueFrom:
                configMapKeyRef:
                  name: clean-old-jobs-configmap
                  key: MAX_PENDING_JOB_AGE_HOURS
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

