apiVersion: batch/v1
kind: Job
metadata:
  name: modify-resource-job
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: modify-job-sa
      containers:
        - name: modify-configmap
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch configmap ingress-nginx-controller -n ingress-nginx --patch '{"data": {"allow-snippet-annotations": "true"}}'
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modify-job-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: modify-job-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: configmap-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-clusterrole
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch"]
