{{- if .Values.monitor_server_listener.enable }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: monitor-server-listener-cron
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  schedule: {{ .Values.monitor_server_listener.pattern | quote }} 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: clean-old-jobs
          containers:
          - name: etcd-defrag-cron
            image: {{ .Values.global.registry }}{{ .Values.monitor_server_listener.image.repository }}:{{ .Values.monitor_server_listener.image.tag }}
          restartPolicy: Never
{{- end }}        