{{- if index .Values "monitor-server" "ingress" "enabled" -}}
{{- $fullName := "monitor-server" -}}
{{- $servicePort := index .Values "monitor-server" "env" "metric_port" -}}
{{- $ingressPath := index .Values "monitor-server" "ingress" "path" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitor-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: monitor-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- end }}


