kind: Service
apiVersion: v1
metadata:
  name: monitor-server
  labels:
    app: monitor-server
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: monitor-server
  ports:
    - protocol: TCP
      port: {{ index .Values "monitor-server" "env""metric_port" }}
      targetPort: {{ index .Values "monitor-server" "env""metric_port" }}