apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-driver-queue
  labels:
    app: pipeline-driver-queue
    group: {{ .Values.lables.group.value }}
    core: "true"
    metrics-group: pipeline-driver-queue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-driver-queue
  template:
    metadata:
      labels:
        app: pipeline-driver-queue
        group: {{ .Values.lables.group.value }}
    spec:
      containers:
        - name: pipeline-driver-queue
          image: "{{ index .Values "pipeline-driver-queue" "image" "repository" }}:{{ index .Values "pipeline-driver-queue" "image" "tag" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ index .Values "pipeline-driver-queue" "env" "metric_port" }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: NODE_ENV
            - name: HKUBE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: KUBE_LOG_LEVEL
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: METRICS_PORT
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      core: "true"
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}