apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-driver-queue
  labels:
    app: pipeline-driver-queue
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics-group: pipeline-driver-queue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-driver-queue
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/pipeline-driver-queue-cm.yaml") . | sha256sum }}
      labels:
        app: pipeline-driver-queue
        group: {{ .Values.labels.group.value }}
    spec:
      serviceAccountName: pipeline-driver-queue-serviceaccount
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}     
      containers:
        - name: pipeline-driver-queue
          image: "{{ .Values.global.registry }}{{ index .Values "pipeline_driver_queue" "image" "repository" }}:{{ index .Values "pipeline_driver_queue" "image" "tag" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.global.resources_enable }}          
          resources:
{{ toYaml .Values.pipeline_driver_queue.resources | indent 12 }}
{{- else }}
          resources: {}
{{- end }}             
          ports:
            - name: http
              containerPort: {{ index .Values "pipeline_driver_queue" "env" "metric_port" }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pipeline-driver-queue-configmap
          env:
{{ include "hkube.fluent_bit.environment" . | indent 12 }}
{{- if eq .Values.env.default_storage "s3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsSecret
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsEndpointUrl
{{- end }}   
{{- if .Values.global.isPrivileged }}            
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
{{- else if .Values.jaeger.external_agent_address }}
            - name: JAEGER_AGENT_SERVICE_HOST
              value: .Values.jaeger.external_agent_address
{{- end }}    
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- if .Values.mongodb.enable }}
            - name: MONGODB_SERVICE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGODB_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: MONGODB_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-database
{{- end }}
{{ include "hkube.fluent_bit.volumemount_full" . | indent 10 }}
{{ include "hkube.fluent_bit.sidecar" . | indent 8 }}
{{ include "hkube.fluent_bit.volume_full" . | indent 6 }}
