apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pipeline-cleaner
  labels:
    group: {{ .Values.labels.group.value }}
    core: "true"
    app: "pipeline-cleaner"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "pipeline-cleaner"
        spec:
          containers:
          - name: pipeline-cleaner
            image: "{{ .Values.global.registry }}{{ index  .Values "pipeline-cleaner" "image" "repository" }}:{{ index .Values "pipeline-cleaner" "image" "tag" }}"
            # resources:
            #   limits:
            #     cpu: 250m
            #     memory: 512Mi
            env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
          restartPolicy: Never

          