kind: Service
apiVersion: v1
metadata:
  name: pipeline-driver-queue
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: pipeline-driver-queue
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: pipeline-driver-queue
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "pipeline-driver-queue" "env""metric_port" "port" }}
      targetPort: {{ index .Values "pipeline-driver-queue" "env""metric_port" "port" }}