kind: Service
apiVersion: v1
metadata:
  name: pipeline-driver
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: pipeline-driver
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: pipeline-driver
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "pipeline-driver" "env""metric_port" "port" }}
      targetPort: {{ index .Values "pipeline-driver" "env""metric_port" "port" }}