# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: pipeline-driver
#   labels:
#     app: pipeline-driver
#     scale-group: pipeline-driver
#     group: {{ .Values.lables.group.value }}
#     core: "true"
# spec:
#   replicas: {{ index .Values "pipeline-driver" "replicaCount" }}
#   selector:
#     matchLabels:
#       app: pipeline-driver
#   template:
#     metadata:
#       labels:
#         app: pipeline-driver
#         group: {{ .Values.lables.group.value }}
#     spec:
#       nodeSelector:
#         core: "true"
#       containers:
#         - name: pipeline-driver
#           image: "{{ index .Values "pipeline-driver" "image" "repository" }}:{{ index .Values "pipeline-driver" "image" "tag" }}"
#           ports:
#             - containerPort: {{ index .Values "pipeline-driver" "env" "metric_port" }}
#           env:
#             - name: NODE_ENV
#               valueFrom:
#                 configMapKeyRef:
#                   name: pipeline-driver-configmap
#                   key: NODE_ENV
#             - name: METRICS_PORT
#               valueFrom:
#                 configMapKeyRef:
#                   name: pipeline-driver-configmap
#                   key: METRICS_PORT
#             - name: AWS_ACCESS_KEY_ID
#               valueFrom:
#                 secretKeyRef:
#                   name: s3-secret
#                   key: awsKey
#             - name: AWS_SECRET_ACCESS_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: s3-secret
#                   key: awsSecret
#             - name: S3_ENDPOINT_URL
#               valueFrom: 
#                 secretKeyRef:
#                   name: s3-secret
#                   key: awsEndpointUrl
#             - name: DEFAULT_STORAGE
#               value: "s3"
#             - name: JAEGER_AGENT_SERVICE_HOST
#               valueFrom:
#                 fieldRef:
#                   fieldPath: status.hostIP
