apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-driver-queue
  labels:
    app: pipeline-driver-queue
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics-group: pipeline-driver-queue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-driver-queue
  template:
    metadata:
      labels:
        app: pipeline-driver-queue
        group: {{ .Values.labels.group.value }}
    spec:
      containers:
        - name: pipeline-driver-queue
          image: "{{ .Values.global.registry }}{{ index .Values "pipeline-driver-queue" "image" "repository" }}:{{ index .Values "pipeline-driver-queue" "image" "tag" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ index .Values "pipeline-driver-queue" "resources" "limits" "cpu" }}
              memory: {{ index .Values "pipeline-driver-queue" "resources" "limits" "memory" }}
            requests:
              cpu: {{ index .Values "pipeline-driver-queue" "resources" "requests" "cpu" }}
              memory: {{ index .Values "pipeline-driver-queue" "resources" "requests" "memory" }}
          ports:
            - name: http
              containerPort: {{ index .Values "pipeline-driver-queue" "env" "metric_port" }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: NODE_ENV
            - name: HKUBE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: KUBE_LOG_LEVEL
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pipeline-driver-queue-configmap
                  key: METRICS_PORT
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
