kind: Service
apiVersion: v1
metadata:
  name: pipeline-driver
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: pipeline-driver
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics: "true"
spec:
  selector:
    group: hkube
    metrics-group: pipeline-drivers
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "pipeline-driver" "env" "metric_port" }}
      targetPort: {{ index .Values "pipeline-driver" "env" "metric_port" }}
