apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: del-deployment-and-jobs
  annotations:
    "helm.sh/hook": post-delete
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: del-deployment-and-jobs
  labels:
    group: {{ .Values.lables.group.value }}
    app: del-deployment-and-jobs
    core: "true"
  annotations:
    "helm.sh/hook": post-delete
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: del-deployment-and-jobs
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: del-deployment-and-jobs
    core: "true"
  annotations:
    "helm.sh/hook": post-delete
subjects:
- kind: ServiceAccount
  name: del-deployment-and-jobs
roleRef:
  kind: Role
  name: del-deployment-and-jobs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "post-del-dep-and-jobs"
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "post-del-dep-and-jobs"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: del-deployment-and-jobs
      restartPolicy: Never
      containers:
      - name: post-del-dep-and-jobs
        image: "{{ index .Values "delete-deployment-and-jobs" "image" "repository" }}:{{ index .Values "delete-deployment-and-jobs" "image" "tag" }}"