apiVersion: batch/v1
kind: Job
metadata:
  name: "post-del-dep-and-jobs"
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "resource-policy": delete-on-completion
    "helm.sh/hook": post-delete,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "post-del-dep-and-jobs"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
      - name: post-del-dep-and-jobs
        image: "{{ index .Values "delete-deployment-and-jobs" "image" "repository" }}:{{ index .Values "delete-deployment-and-jobs" "image" "tag" }}"
        command: ["/usr/local/bin/kubectl", delete deploy -l "metrics-group=algorithm-queue"]
        command: ["/usr/local/bin/kubectl", delete job -l "delete-group=delete-dep-and-jobs"]