apiVersion: batch/v1
kind: Job
metadata:
  name: "post-upgrade-dep-and-jobs"
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "resource-policy": delete-on-completion
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "post-del-dep-and-jobs"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: cleanup-serviceaccount
      restartPolicy: Never
      containers:
      - name: post-del-dep-and-jobs
        image: "{{ .Values.global.registry }}{{ index .Values "delete-deployment-and-jobs" "image" "repository" }}:{{ index .Values "delete-deployment-and-jobs" "image" "tag" }}"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        command:
          - /bin/sh
          - -c
          - |
            /usr/local/bin/kubectl delete deploy -l type=algorithm-queue
            /usr/local/bin/kubectl delete job -l type=worker
            /usr/local/bin/kubectl delete job -l type=pipeline-driver
            /usr/local/bin/kubectl delete deploy -l type=worker-debug
            /usr/local/bin/kubectl delete svc -l type=worker-debug
            /usr/local/bin/kubectl delete ingress -l type=worker-debug
            echo Done

            