apiVersion: batch/v1
kind: Job
metadata:
  name: "pre-del-dep-and-jobs"
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "resource-policy": delete-on-completion
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "post-del-dep-and-jobs"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}   
      serviceAccountName: cleanup-serviceaccount
      restartPolicy: Never
      containers:
      - name: post-del-dep-and-jobs
        image: "{{ .Values.global.registry }}{{ index .Values "delete_deployment_and_jobs" "image" "repository" }}:{{ index .Values "delete_deployment_and_jobs" "image" "tag" }}"
{{- if .Values.global.resources_enable }}          
        resources:
{{ toYaml .Values.delete_deployment_and_jobs.resources | indent 10 }}
{{- else }}
        resources: {}
{{- end }}                
        command:
          - /bin/sh
          - -c
          - |
            /usr/local/bin/kubectl cluster-info
            /usr/local/bin/kubectl delete deploy task-executor
            /usr/local/bin/kubectl delete deploy algorithm-operator
            /usr/local/bin/kubectl delete deploy -l type=algorithm-queue
            /usr/local/bin/kubectl delete job -l type=worker
            /usr/local/bin/kubectl delete job -l type=pipeline-driver
            /usr/local/bin/kubectl delete deploy -l type=worker-debug
            /usr/local/bin/kubectl delete svc -l type=worker-debug
            /usr/local/bin/kubectl delete secret s3-secret
            /usr/local/bin/kubectl delete crd etcdclusters.etcd.database.coreos.com
            echo Done

            