apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager
  labels:
    app: resource-manager
    scale-group: resource-manager
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/resource-manager-cm.yaml") . | sha256sum }}
      labels:
        app: resource-manager
        group: {{ .Values.labels.group.value }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: resource-manager-serviceaccount
      containers:
        - name: resource-manager
          image: "{{ .Values.global.registry }}{{ index .Values "resource_manager" "image" "repository" }}:{{ index .Values "resource_manager" "image" "tag" }}"
{{- if .Values.resource_manager.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.resource_manager.healthcheck.path }}
              port: {{ .Values.resource_manager.healthcheck.port }}
            initialDelaySeconds: {{ .Values.resource_manager.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.resource_manager.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.resource_manager.healthcheck.timeoutSeconds }}
            failureThreshold: {{ .Values.resource_manager.healthcheck.failureThreshold }}
{{- end }}          
          resources:
{{ toYaml .Values.resource_manager.resources | indent 12 }} 
          ports:
            - containerPort: {{ index .Values "resource_manager" "env" "metric_port" }}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: NODE_ENV
            - name: HKUBE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: HKUBE_LOG_LEVEL
            - name: INTERVAL
              value: {{ .Values.resource_manager.env.interval | quote}}
            - name: ALGORITHMS_THRESHOLD_CPU
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: ALGORITHMS_THRESHOLD_CPU
            - name: ALGORITHMS_THRESHOLD_MEM
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: ALGORITHMS_THRESHOLD_MEM
            - name: DRIVERS_THRESHOLD_CPU
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: DRIVERS_THRESHOLD_CPU
            - name: DRIVERS_THRESHOLD_MEM
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: DRIVERS_THRESHOLD_MEM
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: METRICS_PORT
            - name: PROMETHEUS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: PROMETHEUS_ENDPOINT
{{- if .Values.global.isPrivileged }}            
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
{{- else if .Values.jaeger.external_agent_address }}
            - name: JAEGER_AGENT_SERVICE_HOST
              value: .Values.jaeger.external_agent_address
{{- end }}    
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
