apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: resource-manager
  labels:
    app: resource-manager
    scale-group: resource-manager
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager
  template:
    metadata:
      labels:
        app: resource-manager
        group: {{ .Values.lables.group.value }}
    spec:
      {{- if .Values.global.production }}
      nodeSelector:
        core: "true"
      {{- end }}
      serviceAccountName: resource-manager-serviceaccount
      containers:
        - name: resource-manager
          image: "{{ .Values.global.registry }}{{ index .Values "resource-manager" "image" "repository" }}:{{ index .Values "resource-manager" "image" "tag" }}"
          ports:
            - containerPort: {{ index .Values "resource-manager" "env" "metric_port" }}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: NODE_ENV
            - name: HKUBE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: HKUBE_LOG_LEVEL
            - name: INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: INTERVAL
            - name: ALGORITHMS_THRESHOLD_CPU
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: ALGORITHMS_THRESHOLD_CPU
            - name: ALGORITHMS_THRESHOLD_MEM
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: ALGORITHMS_THRESHOLD_MEM
            - name: DRIVERS_THRESHOLD_CPU
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: DRIVERS_THRESHOLD_CPU
            - name: DRIVERS_THRESHOLD_MEM
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: DRIVERS_THRESHOLD_MEM
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: METRICS_PORT
            - name: PROMETHEUS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: resource-manager-configmap
                  key: PROMETHEUS_ENDPOINT
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
