kind: Service
apiVersion: v1
metadata:
  name: resource-manager
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: resource-manager
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: resource-manager
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "resource-manager" "env" "metric_port" }}
      targetPort: {{ index .Values "resource-manager" "env" "metric_port" }}
