apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: results-cleaner
  labels:
    group: {{ .Values.lables.group.value }}
    core: "true"
    app: "results-cleaner"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: results-cleaner
            image: "{{ index  .Values "storage-cleaner" "image" "repository" }}:{{ index .Values "storage-cleaner" "image" "tag" }}"
            env:
            - name: "OBJECT_EXPIRATION_DAYS"
              valueFrom:
                configMapKeyRef:
                  name: results-cleaner-configmap
                  key: OBJECT_EXPIRATION_DAYS
            - name: "DELETE_DESTINATION"
              valueFrom:
                configMapKeyRef:
                  name: results-cleaner-configmap
                  key: DELETE_DESTINATION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsSecret
            - name: S3_ENDPOINT_URL
              valueFrom: 
                secretKeyRef:
                  name: s3-secret
                  key: awsEndpointUrl
            - name: DEFAULT_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: results-cleaner-configmap
                  key: DEFAULT_STORAGE
          restartPolicy: Never
