apiVersion: v1
data:
  awsEndpointUrl: {{ default "" .Values.global.storage.s3.url | b64enc | quote }}
  awsKey: {{ default "" .Values.global.storage.s3.access_key | b64enc | quote }}
  awsSecret: {{ default "" .Values.global.storage.s3.secret_key | b64enc | quote }}
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
