kind: Service
apiVersion: v1
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  selector:
    app: simulator
  ports:
    - protocol: TCP
      port: {{ .Values.simulator.env.port }}
      targetPort: {{ .Values.simulator.env.port }}
