apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
        group: {{ .Values.labels.group.value }}
    spec:
      {{- if .Values.global.production }}
      nodeSelector:
        core: "true"
      {{- end }}
      containers:
        - name: simulator
          image: "{{ .Values.global.registry }}{{ index .Values "simulator" "image" "repository" }}:{{ index .Values "simulator" "image" "tag" }}"
          resources:
{{ toYaml .Values.simulator.resources | indent 12 }} 
          ports:
            - containerPort: {{ .Values.simulator.env.metric_port }}
          env:
            - name: MONITOR_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH
            - name: MONITOR_BACKEND_PATH_SOCKETIO
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH_SOCKETIO
            - name: MONITOR_BACKEND_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_USE_LOCATION
            - name: MONITOR_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_HOST
            - name: MONITOR_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PORT
            - name: isSecure
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_IS_SECURE
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

