{{- if index .Values "simulator" "ingress" "enabled" -}}
{{- $fullName := "simulator" -}}
{{- $servicePort := .Values.simulator.env.port | int -}}
{{/* -------------------- nginx configuration - Ingress -------------------- */}}
{{- if eq .Values.global.ingress.class "nginx" -}}
apiVersion:  {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: dashboard
  annotations:
{{- if .Values.global.ingress.use_snippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{- if .Values.simulator.ingress.alt_path }}
      if ( $request_filename ~ {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.alt_path }} ){
        rewrite ^ {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}/ permanent;
      }
{{- end }}
      rewrite ^({{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }})$ $1/ redirect;
{{- end }}
{{- if .Values.global.ingress.use_regex }}
{{- if and (eq .Values.simulator.ingress.path "/") (not .Values.global.ingress.prefix) }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
{{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- end }}
{{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.global.ingress.requireTls | quote }}
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
{{- if .Values.global.ingress.hostname }}
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
    app: simulator
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
{{- if .Values.global.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.global.ingress.hostname }}
    secretName: {{ $fullName }}-tls-secret
{{- end }}
  rules:
    - http:
        paths:
{{- if .Values.global.ingress.use_regex }}
{{- if and (eq .Values.simulator.ingress.path "/") (not .Values.global.ingress.prefix) }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}(.*)
{{- else }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}(/|$)(.*)
{{- end }}
{{- else }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}
{{- end }}
          backend: {{- include "ingress.backend" (dict "serviceName" $fullName "servicePort" $servicePort "context" $) | nindent 12 }}
          {{- if eq "true" (include "ingress.supportsPathType" .) }}
          pathType: ImplementationSpecific
          {{- end }}
{{- if .Values.simulator.ingress.alt_path }}
{{- if .Values.global.ingress.use_regex }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.alt_path }}(/|$)(.*)
{{- else }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.alt_path }}
{{- end }}
          backend: {{- include "ingress.backend" (dict "serviceName" $fullName "servicePort" $servicePort "context" $) | nindent 12 }}
          {{- if eq "true" (include "ingress.supportsPathType" .) }}
          pathType: ImplementationSpecific
          {{- end }}
{{- end }}

{{- if .Values.global.ingress.hostname }}
      host: {{ .Values.global.ingress.hostname }}
{{- end }}

{{/* -------------------- haproxy configuration - Ingress -------------------- */}}
{{- else if eq .Values.global.ingress.class "haproxy" -}}
apiVersion:  {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: dashboard
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  labels:
    app: hkube
spec:
{{- if .Values.global.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.global.ingress.hostname }}
    secretName: {{ $fullName }}-tls-secret
{{- end }}
  rules:
    - http:
        paths:
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}
          backend: {{- include "ingress.backend" (dict "serviceName" $fullName "servicePort" $servicePort "context" $) | nindent 12 }}
          {{- if eq "true" (include "ingress.supportsPathType" .) }}
          pathType: Prefix
          {{- end }}
{{- if .Values.simulator.ingress.alt_path }}
        - path: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.alt_path }}
          backend: {{- include "ingress.backend" (dict "serviceName" $fullName "servicePort" $servicePort "context" $) | nindent 12 }}
          {{- if eq "true" (include "ingress.supportsPathType" .) }}
          pathType: Prefix
          {{- end }}
{{- end }}

{{- if .Values.global.ingress.hostname }}
      host: {{ .Values.global.ingress.hostname }}
{{- end }}
{{- end }}
{{- end }}