apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/simulator-cm.yaml") . | sha256sum }}
      labels:
        app: simulator
        group: {{ .Values.labels.group.value }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: simulator
          image: "{{ .Values.global.registry }}{{ .Values.simulator.image.repository }}:{{ .Values.simulator.image.tag }}"
          resources:
{{ toYaml .Values.simulator.resources | indent 12 }} 
          ports:
            - containerPort: {{ .Values.simulator.env.metric_port }}
          env:
            - name: HKUBE_SYSTEM_VERSION
              value: {{ .Values.systemversion | quote}}
            - name: MONITOR_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH
            - name: MONITOR_BACKEND_PATH_SOCKETIO
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH_SOCKETIO
            - name: MONITOR_BACKEND_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_USE_LOCATION
            - name: MONITOR_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_HOST
            - name: MONITOR_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PORT
            - name: isSecure
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_IS_SECURE
            - name: BOARD_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PATH
            - name: BOARD_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_USE_LOCATION
            - name: BOARD_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_HOST
            - name: BOARD_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PORT
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

