kind: Service
apiVersion: v1
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: simulator
  ports:
    - protocol: TCP
      port: {{ index .Values "simulator" "env" "metric_port" }}
      targetPort: {{ index .Values "simulator" "env" "metric_port" }}
