{{- if index .Values "simulator" "ingress" "enabled" -}}
{{- $fullName := "simulator" -}}
{{- $servicePort := index .Values "simulator" "env" "metric_port" -}}
{{- $ingressPath := index .Values "simulator" "ingress" "path" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simulator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: simulator
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
{{- if .Values.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
{{- end }}
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname }}
{{- end }}            
{{- end }}
