apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/simulator-cm.yaml") . | sha256sum }}
      labels:
        app: simulator
        group: {{ .Values.labels.group.value }}
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: simulator
          image: "{{ .Values.global.registry }}{{ .Values.simulator.image.repository }}:{{ .Values.simulator.image.tag }}"
{{- if or .Values.global.resources_enable .Values.simulator.resources_enable }}
          resources:
{{ toYaml .Values.simulator.resources | indent 12 }}
{{- else }}
          resources: {}
{{- end }}
          ports:
            - containerPort: {{ .Values.simulator.env.port }}
          env:
            - name: HKUBE_BASE_URL
              value: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}
            - name: HKUBE_SYSTEM_VERSION
              value: {{ .Values.systemversion | quote}}
            - name: API_SERVER_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_PATH
            - name: API_SERVER_BACKEND_DATASOURCES_SERVICE_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_DATASOURCES_SERVICE_PATH   
            - name: API_SERVER_BACKEND_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_USE_LOCATION
            - name: API_SERVER_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_HOST
            - name: KIBANA_URL
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: KIBANA_URL
            - name: GRAFANA_URL
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: GRAFANA_URL
            - name: DATA_SOURCE_IS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: DATA_SOURCE_IS_ENABLE
            - name: API_SERVER_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_PORT
            - name: isSecure
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: API_SERVER_BACKEND_IS_SECURE
            - name: BOARD_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PATH
            - name: BOARD_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_USE_LOCATION
            - name: BOARD_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_HOST
            - name: BOARD_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PORT
            - name: REACT_APP_SITEBASEURL
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: REACT_APP_SITEBASEURL
            - name: ELASTICSEARCH_STRUCTURED_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: ELASTICSEARCH_STRUCTURED_PREFIX
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
