apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/simulator-cm.yaml") . | sha256sum }}
      labels:
        app: simulator
        group: {{ .Values.labels.group.value }}
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: simulator
          image: "{{ .Values.global.registry }}{{ .Values.simulator.image.repository }}:{{ .Values.simulator.image.tag }}"
{{- if .Values.global.resources_enable }}          
          resources:
{{ toYaml .Values.simulator.resources | indent 12 }}
{{- else }}
          resources: {}
{{- end }}
          ports:
            - containerPort: {{ .Values.simulator.env.port }}
          env:
{{ include "hkube.fluent_bit.environment" . | indent 12 }}
            - name: HKUBE_BASE_URL
              value: {{ .Values.global.ingress.prefix }}{{ .Values.simulator.ingress.path }}
            - name: HKUBE_SYSTEM_VERSION
              value: {{ .Values.systemversion | quote}}
            - name: MONITOR_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH
            - name: MONITOR_BACKEND_PATH_SOCKETIO
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH_SOCKETIO
            - name: MONITOR_BACKEND_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_USE_LOCATION
            - name: MONITOR_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_HOST
            - name: MONITOR_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PORT
            - name: isSecure
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_IS_SECURE
            - name: BOARD_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PATH
            - name: BOARD_USE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_USE_LOCATION
            - name: BOARD_HOST
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_HOST
            - name: BOARD_PORT
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: BOARD_PORT
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{ include "hkube.fluent_bit.volumemount_full" . | indent 10 }}
{{ include "hkube.fluent_bit.sidecar" . | indent 8 }}
{{ include "hkube.fluent_bit.volume_full" . | indent 6 }}
