apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
        group: {{ .Values.lables.group.value }}
    spec:
      nodeSelector:
        core: "true"
      containers:
        - name: simulator
          image: "{{ index .Values "simulator" "image" "repository" }}:{{ index .Values "simulator" "image" "tag" }}"
          ports:
            - containerPort: {{ index .Values "simulator" "env" "metric_port" }}
          env:
            - name: MONITOR_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH
            - name: MONITOR_BACKEND_PATH_SOCKETIO
              valueFrom:
                configMapKeyRef:
                  name: simulator-configmap
                  key: MONITOR_BACKEND_PATH_SOCKETIO

