{{- if index .Values "site" "ingress" "enabled" -}}
{{- $servicePort := .Values.site.service.port | int -}}
{{- $ingressPath := .Values.site.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if eq .Values.global.ingress.class "nginx"}}
    ingressClassName: {{ .Values.global.ingress.class | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite   ^(?!.*(?:\.css|\/|\.js|\.svg|\.gif|\.png)$)(.*) $1/ redirect;
{{- else if eq .Values.global.ingress.class "haproxy"}}
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- end }}
  labels:
    app: hkube-site
    app.kubernetes.io/managed-by: Helm
    core: "true"
    heritage: Helm
    release: hkube
  name: hkube-site
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hkube-site
            port:
              number: {{ $servicePort }}
        path: /hkube/site(/|$)(.*)
        pathType: ImplementationSpecific
{{ end }}        