apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hkube-site
  labels:
    app:  hkube-site
    group: {{ .Values.labels.group.value }}
spec:
  selector:
    matchLabels:
      app: hkube-site
  replicas: 1
  template:
    metadata:
      labels:
        app:  hkube-site
    spec:
{{- if or .Values.global.registry_password .Values.global.image_pull_secret.use_existing }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret.name }}
{{- end }}  
      containers:
      - name:  hkube-site
        image:  "{{ .Values.global.registr }}{{ .Values.site.image.repository }}:{{ .Values.site.image.tag }}"
        env :
          - name: BASE_URL
            value: "{{ .Values.site.base_url }}"
          - name: BABEL_DISABLE_CACHE
            value: "1"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: {{ .Values.site.service.port }}
      restartPolicy: Always