kind: Service
apiVersion: v1
metadata:
  name: task-executor
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: task-executor
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: task-executor
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "task-executor" "service" "port" }}
      targetPort: {{ index .Values "task-executor" "service" "port" }}