kind: Service
apiVersion: v1
metadata:
  name: trigger-service
  labels:
    app: trigger-service
    group: {{ .Values.labels.group.value }}
    core: "true"
spec:
  selector:
    app: trigger-service
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "trigger_service" "env" "metric_port" }}
      targetPort: {{ index .Values "trigger_service" "env" "metric_port" }}
