kind: Service
apiVersion: v1
metadata:
  name: trigger-service
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: trigger-service
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  selector:
    app: trigger-service
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values "trigger-service" "env" "metric_port" "port" }}
      targetPort: {{ index .Values "trigger-service" "env" "metric_port" "port" }}