apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webhook-stub-ui
  labels:
    app: webhook-stub-ui
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-stub-ui
  template:
    metadata:
      labels:
        app: webhook-stub-ui
        group: {{ .Values.lables.group.value }}
    spec:
      nodeSelector:
        core: "true"
      containers:
        - name: webhook-stub-ui
          image: "{{ index .Values "webhook-stub-ui" "image" "repository" }}:{{ index .Values "webhook-stub-ui" "image" "tag" }}"
          ports:
            - containerPort: {{ index .Values "webhook-stub-ui" "env" "metric_port" }}
          env:
          - name: PUBLIC_URL
            valueFrom:
                configMapKeyRef:
                  name: webhook-stub-ui-configmap
                  key: PUBLIC_URL