kind: Service
apiVersion: v1
metadata:
  name: worker
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: worker
    group: {{ .Values.labels.group.value }}
    core: "true"
    metrics: "true"
spec:
  selector:
    metrics-group: workers
    group: {{ .Values.labels.group.value }}
  clusterIP: None
  ports:
    - name: metrics
      port: {{ index .Values.worker.metrics.port }}
      targetPort: {{ index .Values.worker.metrics.port }}