apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-executor-serviceaccount
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.Namespace }}
  name: task-executor
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-executor
  namespace: {{ .Values.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
subjects:
- kind: ServiceAccount
  name: task-executor-serviceaccount
roleRef:
  kind: Role
  name: task-executor
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.Namespace }}
  name: task-executor-clusterrole
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-executor-clusterrolebinding
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
subjects:
- kind: ServiceAccount
  name: task-executor-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: task-executor-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.Namespace }}
  name: worker-serviceaccount
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.Namespace }}
  name: delete-jobs
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delete-jobs
  namespace: {{ .Values.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: task-executor
    core: "true"
subjects:
- kind: ServiceAccount
  name: worker-serviceaccount
roleRef:
  kind: Role
  name: delete-jobs
  apiGroup: rbac.authorization.k8s.io