{
 "title": "HKube Streaming",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Pipeline_Name", "label": "Pipeline Name", "query": "label_values(pipelineName)" },
   {
    "name": "Job_ID",
    "label": "Job ID",
    "query": "label_values(hkube_pipeline_driver_streaming_edge_throughput_gauge{pipelineName=\"$Pipeline_Name\"}, pipelineId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput per edge",
   "type": "graph",
   "description": "Throughput per edge(Source to Target)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (hkube_pipeline_driver_streaming_edge_throughput_gauge{pipelineId=\"$Job_ID\"}) by (pipelineName,pipelineId,source,target)",
     "legendFormat": "{{source}} to {{target}}"
    }
   ]
  },
  {
   "title": "Queue size per edge",
   "type": "graph",
   "description": "Queue size per edge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (hkube_pipeline_driver_streaming_edge_queue_size_gauge{pipelineId=\"$Job_ID\"}) by (pipelineId,source,target)",
     "legendFormat": "On {{source}} waiting for {{target}}"
    }
   ]
  },
  {
   "title": "Queue time per edge (ms)",
   "type": "graph",
   "description": "Queue time per edge (Source to Target) ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (hkube_pipeline_driver_streaming_edge_queue_time_gauge{pipelineId=\"$Job_ID\"}) by (pipelineId,source,target)",
     "legendFormat": "On {{source}} waiting for {{target}}"
    }
   ]
  },
  {
   "title": "Processing time per edge (ms)",
   "type": "graph",
   "description": "Processing time per edge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (hkube_pipeline_driver_streaming_edge_processing_time_gauge{pipelineId=\"$Job_ID\"}) by (pipelineId,source,target)",
     "legendFormat": "On {{target}} from {{source}}"
    }
   ]
  }
 ]
}