{
 "title": "HKube Performance & Reliability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline_name",
    "label": "Pipeline Name",
    "query": {
     "query": "label_values(hkube_pipeline_driver_pipeline_net_time_took_histogram_sum, pipeline_name)"
    }
   },
   { "name": "status", "label": "Pipeline Status", "query": "failed,completed" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline net time metrics($status)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelines Count by Status",
     "type": "timeseries",
     "description": "Total pipelines per pipeline name.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hkube_pipeline_driver_pipeline_ended_counter{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}) by (pipeline_name)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Pipeline Net Time - Avg[30s]",
     "type": "timeseries",
     "description": "Average net execution time (time from pipeline driver start to completed/failed) for completed/failed pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_net_time_took_histogram_sum{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_net_time_took_histogram_count{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Net Time - Max/p90 (Slowest)",
     "type": "timeseries",
     "description": "p90 approximation of net execution time for completed pipelines(slowest)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_pipeline_net_time_took_histogram_bucket{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Net Time - Min/p10 (Fastest)",
     "type": "timeseries",
     "description": "p10 approximation of net execution time for completed/failed pipelines(fastest)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.1,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_pipeline_net_time_took_histogram_bucket{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline queue time metrics(all statuses)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelines In Queue Count",
     "type": "timeseries",
     "description": "Total queued pipelines per pipeline name.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\nmax_over_time(hkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}[$__range])\n  -\nmin_over_time(hkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}[$__range])\n)\nand on(pipeline_name)\n(\nsum by (pipeline_name) (\nchanges(hkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}[1m])\n) > 0\n  or\nsum by (pipeline_name) (\nhkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}\nunless\nhkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"} offset 1m\n)\n)\n",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Pipeline Queue Time - Avg [30s]",
     "type": "timeseries",
     "description": "Average queue time (time pipeline spent waiting in queue before execution) for queued pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_queue_time_in_queue_histogram_sum{pipeline_name=~\"$pipeline_name\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Queue Time - Max/p90 (Slowest)",
     "type": "timeseries",
     "description": "p90 approximation of queue time for queued pipelines(slowest)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_queue_time_in_queue_histogram_bucket{pipeline_name=~\"$pipeline_name\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Queue Time - Min/p10 (Fastest)",
     "type": "timeseries",
     "description": "p10 approximation of queue time for queued pipelines(fastest)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.1,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_queue_time_in_queue_histogram_bucket{pipeline_name=~\"$pipeline_name\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline gross time metrics($status)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelines Count by Status",
     "type": "timeseries",
     "description": "Total pipelines per pipeline name.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hkube_pipeline_driver_pipeline_ended_counter{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}) by (pipeline_name)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Pipeline Gross Time - Avg[30s]",
     "type": "timeseries",
     "description": "Average gross execution time (time from pipeline start to completion including queue time) for completed pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_sum{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_count{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Gross Time - Max/p90 (Slowest)",
     "type": "timeseries",
     "description": "p90 approximation of gross execution time for pipelines(slowest)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_bucket{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Estimated Pipeline Gross Time - Min/p10 (Fastest)",
     "type": "timeseries",
     "description": "p10 approximation of gross execution time for pipelines(fastest)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.1,\nsum by (le, pipeline_name) (\nrate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_bucket{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline avg time comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipeline Net Time - Avg [30s]",
     "type": "timeseries",
     "description": "Average net execution time (time from pipeline driver start to completion/failure) for completed/failed pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_net_time_took_histogram_sum{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_net_time_took_histogram_count{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Pipeline Queue Time - Avg [30s](all statuses)",
     "type": "timeseries",
     "description": "Average queue time (time pipeline spent waiting in queue before execution) for completed/failed pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_queue_time_in_queue_histogram_sum{pipeline_name=~\"$pipeline_name\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_queue_time_in_queue_histogram_count{pipeline_name=~\"$pipeline_name\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    },
    {
     "title": "Pipeline Gross Time - Avg [30s]",
     "type": "timeseries",
     "description": "Average gross execution time (time from pipeline start to completion including queue time) for completed/failed pipelines, over a 30 seconds window.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_sum{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n) \n/ \nsum by (pipeline_name) (\n  rate(hkube_pipeline_driver_pipeline_gross_time_took_histogram_count{pipeline_name=~\"$pipeline_name\",status=~\"$status\"}[1m])\n)",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    }
   ]
  }
 ]
}