language: node_js
node_js:
- '10'
branches:
  only:
  - master
install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
  - helm init --client-only
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote set-url --push origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - git remote -v
  - git checkout -f -b version-branch
  - npm version patch -m "bump version [skip ci]"
  - git push origin version-branch:master --follow-tags
script:
  - git config  remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  - ./package.sh
  - curl -f -X POST -H 'accept:application/json' -H "authorization:token ${TRAVIS_API_TOKEN}" -H 'content-type:application/json' -H 'travis-api-version:3' -d "{\"request\":{\"branch\":\"master\",\"message\":\"triggered by ${TRAVIS_REPO_SLUG}\"}}" "https://api.travis-ci.com/repo/kube-HPC%2Fcd-manager/requests"

