apiVersion: v1
kind: Pod
metadata:
  name: pvc-browser
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /mnt/pvc
      name: pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: datadir-hkube-mongodb-0

