apiVersion: v1
appVersion: "1.2"
version: 0.1.2
description: A Helm chart HPC on Kubernetes ( hkube )
name: hkube
home: https://hkube.io/
description: Open source project for HPC over kubernetes
             Hkube is a cloud native open source framework to run distributed pipeline of algorithms built on Kubernetes.
             Hkube allows to run pipelines of algorithms on kubernetes cluster optimally utilizing the available resources, based on user priorities and AI heuristics.
sources:
- https://github.com/kube-HPC
maintainers:
- name: Yehiyam Livne
  email: yehiyam@gmail.com
- name: Eli Maor
  email: linuxem@gmail.com
engine: gotpl
icon: https://avatars3.githubusercontent.com/u/33659277?s=400&u=76702dc2a77eca668b3b4ccb82882398ec2edf9d&v=4
