dependencies:
  - name: etcd
    version: "0.7.2021"
    repository: "https://hkube.org/helm/"
    condition: etcd.enable
  - name: jaeger
    version: "0.27.2009"
    repository: "https://hkube.org/helm/"
    condition: jaeger.enable
  - name: redis-ha
    version: "3.6.1007"
    repository: "https://hkube.org/helm/"
    condition: redis-ha.enable
  - name: nginx-ingress
    version: "1.31.1002"
    repository: "https://hkube.org/helm/"
    condition: nginx-ingress.enable
  - name: minio
    version: "5.0.1027"
    repository: "https://hkube.org/helm/"
    condition: minio.enable
  - name: mongodb
    version: "10.0.1004"
    repository: "https://hkube.org/helm/"
    condition: mongodb.enable
  - name: gitea
    version: "2.1.3008"
    repository: "https://hkube.org/helm/"
    condition: gitea.enable
  - name: keycloak
    version: "21.4.18"
    repository: "https://hkube.org/helm/"
    condition: keycloak.enable
