dependencies:
  - name: etcd
    version: "0.7.2018"
    repository: "https://hkube.io/helm/"
    condition: etcd.enable
  - name: jaeger
    version: "0.27.2006"
    repository: "https://hkube.io/helm/"
    condition: jaeger.enable
  - name: redis-ha
    version: "3.6.1005"
    repository: "https://hkube.io/helm/"
    condition: redis-ha.enable
  - name: nginx-ingress
    version: "1.31.1002"
    repository: "https://hkube.io/helm/"
    condition: nginx-ingress.enable
  - name: minio
    version: "5.0.1024"
    repository: "https://hkube.io/helm/"
    condition: minio.enable
  - name: mongodb
    version: "10.0.1001"
    repository: "https://hkube.io/helm/"
    condition: mongodb.enable
  - name: gitea
    version: "2.1.3006"
    repository: "https://hkube.io/helm/"
    condition: gitea.enable    
