dependencies:
- name: algorithm-queue-svc
  version: "0.1.0"
  repository: "file://../algorithm-queue-svc"
- name: trigger-service
  version: "0.1.0"
  repository: "file://../trigger-service"
- name: job-cleaner
  version: "0.1.0"
  repository: "file://../job-cleaner"
