dependencies:
- name: mini
  version: "0.1.2"
  repository: "file://../mini"
  condition: minikube.enabled
- name: thirdparty
  version: "0.1.2"
  repository: "file://../thirdparty"
  condition: thirdparty.enabled
