dependencies:
- name: thirdparty
  version: "0.0.3"
  repository: "http://hkube.io/helm/"
  tags:
    - production
- name: mini-thirdparty
  version: "0.2.0"
  repository: "http://hkube.io/helm/"
  tags:
    - minikube
