apiVersion: v1
kind: Service
metadata:
  name: {{ template "simulator.fullname" . }}
  labels:
    app: {{ template "simulator.name" . }}
    chart: {{ template "simulator.chart" . }}
    group: {{ .Values.lables.group.value }}
    #core: {{ .Values.lables.core.value }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "simulator.name" . }}
    release: {{ .Release.Name }}
