apiVersion: v1
kind: Service
metadata:
  name: {{ template "worker-svc.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: {{ template "worker-svc.name" . }}
    chart: {{ template "worker-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "worker-svc.name" . }}
    release: {{ .Release.Name }}
    group: {{ .Values.lables.group.value }}
    core: "true"
    ports:
    - name: metrics
      port: 3001
      targetPort: 3001