{
 "title": "HKube Algorithms",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Queued Algorithms",
   "type": "graph",
   "description": "Current number of algorithms (by type) waiting in algorithm queues.\nNotice it doesn't include algorithms which are handled quicker than scrape interval!",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_algorithm_queue_queue_amount_gauge) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Start Rate [5 min]",
   "type": "graph",
   "description": "Start rate (algorithms per minute) for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_worker_started_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Success Rate [5 min]",
   "type": "graph",
   "description": "Success rate (algorithms per minute) for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_worker_succeeded_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Failure Rate [5 min]",
   "type": "graph",
   "description": "Failure rate (algorithms per minute) for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_worker_failed_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Average Time in Queue",
   "type": "graph",
   "description": "Total average time-in-queue for each algorithm type",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_algorithm_queue_time_in_queue_histogram_sum) by (algorithm_name) / sum(hkube_algorithm_queue_time_in_queue_histogram_count) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Median Time in  Queue [5 min]",
   "type": "graph",
   "description": "Median (50% percentile) value of time-in-queue for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hkube_algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms 95% Percentile Time in  Queue [5 min]",
   "type": "graph",
   "description": "95% percentile value of time-in-queue for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hkube_algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Average Total Runtime",
   "type": "graph",
   "description": "Total average runtime for each algorithm type",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_worker_net_histogram_sum) by (algorithm_name) / sum(hkube_worker_net_histogram_count) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Median Total Runtime [5 min]",
   "type": "graph",
   "description": "Median (50% percentile) value of time-in-queue for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hkube_worker_net_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms 95% Percentile Total Runtime [5 min]",
   "type": "graph",
   "description": "95% percentile value of time-in-queue for each algorithm type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hkube_worker_net_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Algorithms [5 min]",
   "type": "graph",
   "description": "How many CPU cores are used for each algorithm",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(\nmax(kube_pod_labels{label_algorithm_name!~\"\"}) by (label_algorithm_name, pod)\n                   * on(pod)\n                   group_right(label_algorithm_name)\n                       sum by(pod) (\n                           rate(container_cpu_usage_seconds_total{container=\"algorunner\"}[5m])\n                       )\n                   ) by (label_algorithm_name)",
     "legendFormat": "{{label_algorithm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Algorithms",
   "type": "graph",
   "description": "How much memory is used by each algorithm",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\nmax(kube_pod_labels{label_algorithm_name!~\"\"}) by (label_algorithm_name, pod)\n                   * on(pod)\n                   group_right(label_algorithm_name)\n                       sum by(pod) (\n                           container_memory_working_set_bytes\n                       )\n                   ) by (label_algorithm_name) / 1000",
     "legendFormat": "{{label_algorithm_name}}"
    }
   ]
  }
 ]
}