{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api-server.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: {{ template "api-server.name" . }}
    chart: {{ template "api-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- end }}

  # rules:
  # - http:
  #     paths:
  #       - path: /hkube/api-server
  #         backend:
  #           serviceName: api-server
  #           servicePort: 3000
  #       - path: /hkube/simulator
  #         backend:
  #           serviceName: simulator
  #           servicePort: 9050
  #       - path: /hkube/monitor-server
  #         backend:
  #           serviceName: monitor-server
  #           servicePort: 30010
  #       - path: /hkube/webhook-stub-ui
  #         backend:
  #           serviceName: webhook-stub-ui
  #           servicePort: 3002