apiVersion: v1
kind: Service
metadata:
  name: {{ template "pipeline-driver-queue.fullname" . }}
  labels:
    app: {{ template "pipeline-driver-queue.name" . }}
    chart: {{ template "pipeline-driver-queue.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "pipeline-driver-queue.name" . }}
    release: {{ .Release.Name }}

kind: Service
apiVersion: v1
metadata:
  name: pipeline-driver-queue
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: pipeline-driver-queue
    group: hkube
    core: "true"
spec:
  selector:
    app: pipeline-driver-queue
  clusterIP: None
  ports:
    - name: metrics
      port: 3000
      targetPort: 3000

