apiVersion: v1
kind: Service
metadata:
  name: {{ template "trigger-service.fullname" . }}
  labels:
    app: {{ template "trigger-service.name" . }}
    chart: {{ template "trigger-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "trigger-service.name" . }}
    release: {{ .Release.Name }}
  ports:
     - name: metrics
       port: {{ .Values.service.port }}
       targetPort: {{ .Values.service.port }}