---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifacts-registry-configmap
data:
  NEXUS_CONTEXT:  {{ .Values.global.ingress.prefix }}{{index .Values "artifacts_registry" "ingress" "path" |trimPrefix "/" | quote}}
  PORT: {{index .Values "artifacts_registry" "env" "port" | quote}}

