---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifacts-registry-configmap
data:
  NEXUS_CONTEXT: {{index .Values "artifacts-registry" "env" "context" | quote}}
  PORT: {{index .Values "api_server" "env" "port" | quote}}

