---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caching-service-configmap
data:
  NODE_ENV: {{ .Values.env.node_env }}
  DEFAULT_STORAGE: {{index .Values "env" "default_storage" | quote}}
  STORAGE_ENCODING: {{index .Values.global.storage.encoding | quote}}
{{- if eq .Values.env.default_storage "fs" }}
  BASE_FS_ADAPTER_DIRECTORY: {{ .Values.global.storage.fs.base_directory | quote}}
{{- end }}  
  PORT: {{index .Values "caching_service" "env" "port" | quote}}
  CLUSTER_NAME: {{ .Values.global.clusterName | quote}}
