---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clean-old-jobs-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  MAX_COMPLETED_JOB_AGE_HOURS: {{ index .Values "clean-old-jobs" "env" "max_completed_job_age_hours" | quote }}
  CLEAN_CRON: {{ index .Values "clean-old-jobs" "env" "clean_cron" | quote }}
