---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clean-old-jobs-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  MAX_COMPLETED_JOB_AGE_HOURS: {{ index .Values "clean_old_jobs" "env" "max_completed_job_age_hours" | quote }}
  MAX_FAILED_JOB_AGE_HOURS: {{ index .Values "clean_old_jobs" "env" "max_failed_job_age_hours" | quote }}
  MAX_PENDING_JOB_AGE_HOURS: {{ index .Values "clean_old_jobs" "env" "max_pending_job_age_hours" | quote }}
  CLEAN_CRON: {{ index .Values "clean_old_jobs" "env" "clean_cron" | quote }}
  HKUBE_LOG_LEVEL: {{ index .Values "clean_old_jobs" "env" "hkube_log_level" | quote }}
