---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-service-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  BASE_URL_PATH: {{ .Values.datasource_service.env.base_url_path | quote}}
  DEFAULT_STORAGE: {{ .Values.env.default_storage | quote}}
  STORAGE_ENCODING: {{ .Values.global.storage.encoding | quote}}
  STORAGE_RESULTS_THRESHOLD: {{ .Values.global.storage.storageResultsThreshold | quote}}
{{- if eq .Values.env.default_storage "fs" }}
  BASE_FS_ADAPTER_DIRECTORY: {{ .Values.global.storage.fs.base_directory | quote}}
{{- end }}  
  METRICS_PORT: {{ .Values.datasource_service.env.metric_port | quote}}
  PORT: {{ .Values.datasource_service.env.port | quote}}
  INGRESS_PREFIX: {{ .Values.global.ingress.prefix | quote}}
  CLUSTER_NAME: {{ .Values.global.clusterName | quote}}

