---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hkube-gc-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  MAX_COMPLETED_JOB_AGE_HOURS: {{ .Values.hkube_gc.env.max_completed_job_age_hours | quote }}
  MAX_FAILED_JOB_AGE_HOURS: {{ .Values.hkube_gc.env.max_failed_job_age_hours | quote }}
  MAX_PENDING_JOB_AGE_HOURS: {{ .Values.hkube_gc.env.max_pending_job_age_hours | quote }}
  CLEAN_CRON: {{ .Values.hkube_gc.env.clean_cron | quote }}
  HKUBE_LOG_LEVEL: {{ .Values.hkube_gc.env.hkube_log_level | quote }}
