{{- if .Values.mongodb.enable  }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    group: hkube
    core: "true"
type: Opaque
data:
  mongodb-root-password:  {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-password:  {{ .Values.mongodb.auth.password | b64enc | quote }}
  mongodb-username:  {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-database:  {{ .Values.mongodb.auth.database | b64enc | quote }}
{{- end }}
