{{- if .Values.mongodb.enable  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  MONGODB_CONNECTION_METHOD: {{ ternary "mongodb+srv" "mongodb" (eq .Values.mongodb.architecture "replicaset") }}
  MONGODB_SERVICE_HOST: {{ .Release.Name }}-mongodb-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterName }}
  MONGODB_TLS: {{ .Values.mongodb.tls.enabled | quote}}
{{- end }}