---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-server-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  DEFAULT_STORAGE: {{index .Values "env" "default_storage" | quote}}
  STORAGE_ENCODING: {{index .Values.global.storage.encoding | quote}}
{{- if eq .Values.env.default_storage "fs" }}
  BASE_FS_ADAPTER_DIRECTORY: {{ .Values.global.storage.fs.base_directory | quote}}
{{- end }}
  CLUSTER_NAME: {{ .Values.global.clusterName | quote}}
  JAEGER_QUERY_SERVICE_HOST: {{ .Values.monitor_server.env.jaeger_query_service_host | quote }}
  JAEGER_QUERY_SERVICE_PORT: {{ .Values.monitor_server.env.jaeger_query_service_port | quote }}


