---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-driver-queue-configmap
data:
  NODE_ENV: {{.Values.env.node_env}}
  KUBE_LOG_LEVEL: {{index .Values "pipeline_driver_queue" "env" "hkube_log_level" | quote}}
  METRICS_PORT: "{{index .Values "pipeline_driver_queue" "env" "metric_port"}}"
  CHECK_QUEUE_INTERVAL: {{ .Values.pipeline_driver_queue.env.check_queue_interval | quote }}
