---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-cleaner-configmap
data:
  OBJECT_EXPIRATION_DAYS: "{{index .Values "storage-cleaner" "env" "object_expiration_days"}}"
  DEFAULT_STORAGE: {{index .Values "env" "default_storage"}}
