apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-configmap
data:
  NODE_ENV: {{ .Values.env.node_env }}
  BASE_URL_PATH: {{ .Values.api-server.env.base_url_path }}
  DEFAULT_STORAGE: {{ .Values.api-server.env.default_storage }}