apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-manager-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: resource-manager
    core: "true"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "resource-manager.fullname" . }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: resource-manager-role
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-manager-clusterrole
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: {{ template "resource-manager.name" . }}
    core: "true"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager-clusterrolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: {{ template "resource-manager.name" . }}
    core: "true"
subjects:
- kind: ServiceAccount
  name: resource-manager-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: resource-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "resource-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: {{ template "resource-manager.name" . }}
    core: "true"
subjects:
- kind: ServiceAccount
  name: resource-manager-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "resource-manager.name" . }}
  apiGroup: rbac.authorization.k8s.io
