apiVersion: v1
kind: Service
metadata:
  name: {{ template "algorithm-queue-svc.fullname" . }}
  labels:
    app: {{ template "algorithm-queue-svc.name" . }}
    chart: {{ template "algorithm-queue-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "algorithm-queue-svc.name" . }}
    release: {{ .Release.Name }}