apiVersion: v1
kind: ServiceAccount
metadata:
  name: algorithm-operator-serviceaccount
  labels:
    group: {{ .Values.lables.group.value }}
    app: algorithm-operator
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.Namespace }}
  name: algorithm-operator
  labels:
    group: {{ .Values.lables.group.value }}
    app: algorithm-operator
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: algorithm-operator
  namespace: {{ .Values.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: algorithm-operator
    core: "true"
subjects:
- kind: ServiceAccount
  name: algorithm-operator-serviceaccount
roleRef:
  kind: Role
  name: algorithm-operator
  apiGroup: rbac.authorization.k8s.io
---