apiVersion: v1
kind: Service
metadata:
  name: algorithm-operator
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: algorithm-operator
    chart: algorithm-operator
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  clusterIP: None
  type: {{ .Values.algorithmoperator.service.type }}
  ports:
    - port: {{ .Values.algorithmoperator.service.port }}
      targetPort: {{ .Values.algorithmoperator.service.port }}
      protocol: TCP
  selector:
    app: algorithm-operator
    release: {{ .Release.Name }}