apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: algorithm-operator
  labels:
    app: algorithm-operator
    release: algorithm-operator
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algorithm-operator  
  template:
    metadata:
      labels:
        app: algorithm-operator
        release: algorithm-operator
        group: {{ .Values.lables.group.value }}
    spec:
      serviceAccountName: algorithm-operator-serviceaccount
      containers:
        - name: algorithm-operator
          image: "{{ index .Values "algorithm-operator" "image" "repository" }}:{{ index .Values "algorithm-operator" "image" "tag" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ index .Values "algorithm-operator" "service" "port" }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.node_env }}
            - name: METRICS_PORT
              value: "{{ .Values.env.metrics_port }}"
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      core: "true"
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
