{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api-server" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: api-server
    chart: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- end }}