apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
    chart: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values "api-server" "service" "port" }}
      targetPort: {{ index .Values "api-server" "service" "port" }}
      protocol: TCP
  selector:
    app: api-server
    release: {{ .Release.Name }}
