apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
    chart: api-server
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api-server
        release: {{ .Release.Name }}
        group: {{ .Values.lables.group.value }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ index .Values "api-server" "image" "repository" }}:{{ index .Values "image" "tag" }}"
          imagePullPolicy: {{ index .Values "api-server" "image" "pullPolicy" }}
          ports:
            - containerPort: {{ index .Values "api-server" "service" "port" }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.node_env }}
            - name: BASE_URL_PATH
              value: {{ .Values.env.base_url_path }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsSecret
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: awsEndpointUrl
            - name: DEFAULT_STORAGE
              value: {{ .Values.env.default_storage }}
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      core: "true"
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}