# Source: jaeger/templates/agent-ds.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: jaeger-jaeger-agent
  labels:
    app: jaeger
    jaeger-infra: agent-daemonset
    chart: jaeger-0.3.5
    component: agent
    heritage: Tiller
    release: jaeger
    group: {{ .Values.lables.group.value }}
    thirdparty: "true"
spec:
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
        release: jaeger
        jaeger-infra: agent-instance
        group: {{ .Values.lables.group.value }}
        thirdparty: "true"
    spec:
      nodeSelector:
        third-party: "true"
      containers:
      - name: jaeger-jaeger-agent
        image: jaegertracing/jaeger-agent:1.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: COLLECTOR_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger-jaeger
              key: collector.host-port
        ports:
        - containerPort: 5775
          hostPort: 5775
          protocol: UDP
        - containerPort: 6831
          hostPort: 6831
          protocol: UDP
        - containerPort: 6832
          hostPort: 6832
          protocol: UDP
        - containerPort: 5778
          hostPort: 5778
          protocol: TCP
        resources:
          {}
