# Source: jaeger/templates/query-deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger-jaeger-query
  labels:
    app: jaeger
    jaeger-infra: query-deployment
    chart: jaeger-0.3.5
    component: query
    heritage: Tiller
    release: jaeger
    group: {{ .Values.lables.group.value }}
    thirdparty: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        component: query
        release: jaeger
        jaeger-infra: query-pod
        group: {{ .Values.lables.group.value }}
        thirdparty: "true"
    spec:
      nodeSelector:
        third-party: "true"
      containers:
      - name: jaeger-jaeger-query
        image: jaegertracing/jaeger-query:1.4.1
        imagePullPolicy: IfNotPresent
        env:
          - name: QUERY_BASE_PATH
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: query.base-path
          - name: SPAN_STORAGE_TYPE
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: span-storage.type
          - name: CASSANDRA_SERVERS
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: cassandra.servers
          - name: CASSANDRA_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: cassandra.port
          - name: CASSANDRA_KEYSPACE
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: cassandra.keyspace
          - name: QUERY_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: query.port
          - name: QUERY_HEALTH_CHECK_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger-jaeger
                key: query.health-check-http-port
        ports:
        - containerPort: 16686
          protocol: TCP
        resources:
          {}
          
        readinessProbe:
          httpGet:
            path: /
            port: 16687
      dnsPolicy: ClusterFirst
      restartPolicy: Always