apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: monitor-server
  labels:
    app: monitor-server
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-server
  template:
    metadata:
      labels:
        app: monitor-server
        group: {{ .Values.lables.group.value }}
    spec:
      nodeSelector:
        core: "true"
      containers:
        - name: monitor-server
          image: "{{ index  .Values "monitor-server" "image" "repository" }}:{{ index .Values "monitor-server" "image" "tag" }}"
          ports:
            - containerPort: 30010
          volumeMounts:
            - name: versions-config
              mountPath: /versions
      volumes:
        - name: versions-config
          configMap:
            name: hkube-versions