apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-driver-queue
  labels:
    app: pipeline-driver-queue
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
    metrics-group: pipeline-driver-queue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-driver-queue
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pipeline-driver-queue
        group: {{ .Values.lables.group.value }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ index .Values "pipeline-driver-queue" "image" "repository" }}:{{ index .Values "pipeline-driver-queue" "image" "tag" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ index .Values "pipeline-driver-queue" "service" "port" }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.node_env }}
            - name: HKUBE_LOG_LEVEL
              value: "{{ .Values.env.hkube_log_level }}"
            - name: METRICS_PORT
              value: "{{ .Values.env.metrics_port }}"
            - name: JAEGER_AGENT_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      core: "true"
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}