apiVersion: batch/v1
kind: Job
metadata:
  name: "post-del-dep-and-jobs"
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "post-del-dep-and-jobs"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: del-deployment-and-jobs
      restartPolicy: Never
      containers:
      - name: post-del-dep-and-jobs
        image: "linuxem/del-dep-and-jobs:v1.0.0"
    
