apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-manager-serviceaccount
  labels:
    group: hkube
    app: resource-manager
    core: "true"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: resource-manager
  labels:
    group: hkube
    app: resource-manager-role
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager-clusterrole
  labels:
    group: hkube
    app: resource-manager
    core: "true"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager-clusterrolebinding
  labels:
    group: hkube
    app: resource-manager
    core: "true"
subjects:
- kind: ServiceAccount
  name: resource-manager-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager
  namespace: default
  labels:
    group: hkube
    app: resource-manager
    core: "true"
subjects:
- kind: ServiceAccount
  name: resource-manager-serviceaccount
roleRef:
  kind: Role
  name: resource-manager
  apiGroup: rbac.authorization.k8s.io