{{- if index .Values "webhook-stub-ui" "ingress" "enabled" -}}
{{- $fullName := "webhook-stub-ui" -}}
{{- $servicePort := index .Values "webhook-stub-ui" "service" "port" -}}
{{- $ingressPath := index .Values "webhook-stub-ui" "ingress" "path" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webhook-stub-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: webhook-stub-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- end }}