apiVersion: v1
kind: Service
metadata:
  name: {{ template "task-executor.fullname" . }}
  labels:
    app: {{ template "task-executor.name" . }}
    chart: {{ template "task-executor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "task-executor.name" . }}
    release: {{ .Release.Name }}