apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pipeline-driver.fullname" . }}
  labels:
    app: {{ template "pipeline-driver.name" . }}
    chart: {{ template "pipeline-driver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pipeline-driver.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pipeline-driver.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
           - name: NODE_ENV
             value: {{ .Values.env.node_env }}
           - name: METRICS_POTR
             value: {{ .Values.env.metrics_port }}
           - name: AWS_ACCESS_KEY_ID
             value: {{ .Values.env.aws_access_key_id }}
           - name: AWS_SECRET_ACCESS_KEY
             value: {{ .Values.env.aws_secret_access_key }}
           - name: S3_ENDPOINT_URL
             value: {{ .Values.env.s3_endpoint_url }}
           - name: DEFAULT_STORAGE
             value: {{ .Values.env.default_storage }}
           - name: JAEGER_AGENT_SERVICE_HOST
             value: {{ .Values.env.jaeger_agent_service_host }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        core: "true"
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
