{
 "title": "HKube Pipelines",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Queued Pipelines",
   "type": "graph",
   "description": "Current number of pipelines (by type) waiting in pipeline driver queues.\nNotice it doesn't include pipeline which are handled quicker than scrape interval!",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_pipeline_driver_queue_amount_gauge) by (pipeline_name)",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Start Rate [5 min]",
   "type": "graph",
   "description": "Start rate (pipelines per minute) for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_pipeline_driver_queue_counter_counter[5m])) by (pipeline_name) * 60",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Success Rate [5 min]",
   "type": "graph",
   "description": "Success rate (pipelines per minute) for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_api_server_pipelines_gross_counter{status='completed'}[5m])) by (pipeline_name) * 60",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Failure Rate [5 min]",
   "type": "graph",
   "description": "Failure rate (pipelines per minute) for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hkube_api_server_pipelines_gross_counter{status='failed'}[5m])) by (pipeline_name) * 60",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Average Time in Queue",
   "type": "graph",
   "description": "Total average time-in-queue for each pipeline type",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_pipeline_driver_queue_time_in_queue_histogram_sum) by (le, pipeline_name) /sum(hkube_pipeline_driver_queue_time_in_queue_histogram_count) by (le, pipeline_name)",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Median Time in  Queue [5 min]",
   "type": "graph",
   "description": "Median (50% percentile) value of time-in-queue for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hkube_pipeline_driver_queue_time_in_queue_histogram_bucket[5m])) by (le, pipeline_name))",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines 95% Percentile Time in  Queue [5 min]",
   "type": "graph",
   "description": "95% percentile value of time-in-queue for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hkube_pipeline_driver_queue_time_in_queue_histogram_bucket[5m])) by (le, pipeline_name))",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Average Total Runtime",
   "type": "graph",
   "description": "Total average runtime for each pipeline type",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(hkube_pipeline_driver_pipelines_net_histogram_sum) by (pipeline_name) / sum(hkube_pipeline_driver_pipelines_net_histogram_count) by (pipeline_name)",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Pipelines Median Total Runtime [5 min]",
   "type": "graph",
   "description": "Median (50% percentile) value of time-in-queue for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hkube_pipeline_driver_pipelines_net_histogram_bucket[5m])) by (le, pipeline_name))",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  },
  {
   "title": "Jobs 95% Percentile Total Runtime [5 min]",
   "type": "graph",
   "description": "95% percentile value of time-in-queue for each pipeline type, measured over 5 min",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hkube_pipeline_driver_pipelines_net_histogram_bucket[5m])) by (le, pipeline_name))",
     "legendFormat": "{{pipeline_name}}"
    }
   ]
  }
 ]
}