# Default values for monitor-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: default

image:
  repository: hkube/monitor-server
  tag: latest #v1.1.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 30010

lables:
   group:
     value: hkube
   core:
     value: true

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /hkube/monitor-server

  hosts: {}
  
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
