# apiVersion: apps/v1beta2
# kind: Deployment
# metadata:
#   name: {{ template "core.fullname" . }}
#   labels:
#     app: {{ template "core.name" . }}
#     chart: {{ template "core.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
#     group: {{ .Values.lables.group.value }}
#     core: "true"
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: {{ template "core.name" . }}
#       release: {{ .Release.Name }}
#   template:
#     metadata:
#       annotations:
#         checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
#       labels:
#         app: {{ template "core.name" . }}
#         release: {{ .Release.Name }}
#         group: {{ .Values.lables.group.value }}
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: 80
#               protocol: TCP
#           resources:
# {{ toYaml .Values.resources | indent 12 }}
#     {{- with .Values.nodeSelector }}
#       nodeSelector:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.tolerations }}
#       tolerations:
# {{ toYaml . | indent 8 }}
#     {{- end }}
