apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
    awsEndpointUrl: "http://10.32.10.24:9000"
    awsKey: "agambstorage"
    awsSecret1: "234eqndbpuCkGtH85KSyK/xAv3xuqdOpM3fKOLYlrSerpdKoG1FYy3kh6ArceL+yDwTvQOgs47xYO/ktnNzEeg=="
