systemversion: 1.1.237

api-server:
     image:
       tag: v1.1.47
worker:
  image:
    tag: v1.1.29
pipeline-driver:
  image:
    tag: v1.1.13
algorunner:
  image:
    tag: v1.1.4
simulator:
  image:
    tag: v1.1.6
webhook-stub-ui:
  image:
    tag: v1.1.2
algorithm-example:
  image:
    tag: v1.1.7
deployment:
  image:
    tag: v1.1.32
monitor-server:
  image:
    tag: v1.1.8
algorithm-queue:
  image:
    tag: v1.1.15
resource-manager:
   image:
     tag: v1.1.17
task-executor:
  image:
    tag: v1.1.37
trigger-service:
  image:
    tag: v1.1.12
algorithm-operator:
  image:
    tag: v1.1.8
clean-old-jobs:
  image:
    tag: v1.1.1
