apiVersion: v1
kind: Service
metadata:
  name: {{ template "algorithm-operator.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: {{ template "algorithm-operator.name" . }}
    chart: {{ template "algorithm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "algorithm-operator.name" . }}
    release: {{ .Release.Name }}