kind: Service
apiVersion: v1
metadata:
  name: etcd-client
  labels:
    app: etcd
    group: hkube
spec:
  selector:
    app: etcd
  ports:
    - name: client
      protocol: TCP
      port: 4001
      targetPort: 4001
    - name: peer
      protocol: TCP
      port: 2380
      targetPort: 2380
