# This is a basic workflow to help you get started with Actions

name: CI-PROMOTE

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      HKUBE_VERSION:
        description: The version to promote from dev to prod
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # disable lint for now because of https://github.com/helm/helm/issues/8615
      # - run: helm lint hkube/
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: envs
        run: |
            echo HKUBE_VERSION=${HKUBE_VERSION} >> $GITHUB_ENV
        env:
          HKUBE_VERSION: '${{ github.event.inputs.HKUBE_VERSION }}'
      - run: |
          git remote -v
          git fetch
          git checkout -b gh-pages origin/gh-pages
          mkdir -p /tmp/charts
          cp dev/hkube-${HKUBE_VERSION}.tgz /tmp/charts
          helm repo index --merge ./index.yaml /tmp/charts/
          cp dev/hkube-${HKUBE_VERSION}.tgz .
          git add .
          git commit -m "update charts"
          git push
      
  