apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-old-jobs
  labels:
    group: {{ .Values.lables.group.value }}
    core: "true"
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: clean-old-jobs
          containers:
          - name: clean-old-jobs
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
            - name: "MAX_COMPLETED_JOB_AGE_HOURS"
              value: "{{ .Values.env.max_completed_job_age_hours }}"
          restartPolicy: Never
              
